language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install https://github.com/karma-runner/grunt-karma/archive/eb956ca331deae1c7f9c4555cbf6558df1734146.tar.gz'
  - 'npm install -g bower grunt-cli'
  - 'bower install'

after_script:
  - 'node_modules/coveralls/bin/coveralls.js < coverage/PhantomJS\ 1.8\ \(Linux\)/lcov.info'
